name: Terraform Deploy with Remote State

on:
  push:
    branches:
      - master

jobs:
  bootstrap:
    name: Bootstrap Terraform State
    runs-on: ubuntu-latest
    outputs:
      storage_account_name: ${{ steps.bootstrap.outputs.storage_account_name }}
      resource_group_name: ${{ steps.bootstrap.outputs.resource_group_name }}
      container_name: ${{ steps.bootstrap.outputs.container_name }}
      state_key: ${{ steps.bootstrap.outputs.state_key }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Init & Apply bootstrap
        working-directory: .
        run: |
          terraform init
          terraform plan
          terraform apply -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

      - name: Capture Outputs
        id: bootstrap
        run: |
          echo "storage_account_name=$(terraform output -raw storage_account_name)" >> "$GITHUB_OUTPUT"
          echo "resource_group_name=$(terraform output -raw resource_group_name)" >> "$GITHUB_OUTPUT"
          echo "container_name=$(terraform output -raw container_name)" >> "$GITHUB_OUTPUT"
          echo "state_key=$(terraform output -raw state_key)" >> "$GITHUB_OUTPUT"

  deploy:
    name: Deploy Infra with Backend
    runs-on: ubuntu-latest
    needs: bootstrap

    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init with Remote Backend
        working-directory: ./infra
        run: |
          terraform init \
            -backend-config=\"resource_group_name=${{ needs.bootstrap.outputs.resource_group_name }}\" \
            -backend-config=\"storage_account_name=${{ needs.bootstrap.outputs.storage_account_name }}\" \
            -backend-config=\"container_name=${{ needs.bootstrap.outputs.container_name }}\" \
            -backend-config=\"key=${{ needs.bootstrap.outputs.state_key }}\"

      - name: Terraform Apply
        working-directory: ./infra
        run: terraform plan
        env:
            ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
            ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
            ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
            ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

      - name: Terraform Apply
        working-directory: ./infra
        run: terraform apply -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
